name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
    tags: '*'

jobs:		
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project -e 'import Pkg; Pkg.instantiate'
          julia --project src/Intro.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
